### ISSUE TITLE
Feature Request: YouTube Integration

### ISSUE THREAD

**Issue by therealrodk** [Cloud-Player/web#63]
Perhaps you could add YouTube login, as well. Then, people will have access to their existing playlists. If not, it shouldn't be too hard to save a YouTube playlist locally, i.e., by allowing users to "like" them, or whatever, from within Cloud Player, and simply saving a link/reference for each song/video. Ultimately, it would be cool to have an option to shuffle all songs from both Soundcloud and YouTube playlists.

**Comment by Zarlex** [comment]
The youtube integration is currently work in progress but will be releases soon
