### ISSUE TITLE
Media Keys Not Working

### ISSUE THREAD

**Issue by therealrodk** [Cloud-Player/web#65]
The media keys on my keyboard worked the first time I used Cloud Player (i.e., to control Cloud Player), but haven't worked since.

**Comment by Zarlex** [comment]
Are you using the desktop application or do you have a browser plugin to sue your media keys for webpages?
Which OS (and browser) are you using?

**Comment by therealrodk** [comment]
I am using the desktop app on macOS 10.13.2, and I don't use the media keys for anything but iTunes. I always make sure iTunes is closed when I use Cloud Player so it won't get confused, but it still doesn't work.

**Comment by Zarlex** [comment]
Are you using the [latest](https://github.com/Cloud-Player/desktop-app/releases/tag/v1.0.0) client v1.0.0? Can you try to reinstall it? I'm also the native player on macOS 10.13.2 and everything is working fine for me

**Comment by therealrodk** [comment]
After re-installation the keys seem to be working. Thanks.
