### ISSUE TITLE
Empty playlist

### ISSUE THREAD

**Issue by ParthJai** [Cloud-Player/web#77]
I had saved about 60 tracks in a playlist. Those tracks were in the playlist until the day before yesterday and today it says no track in the playlist. It annoys you beyond limits when you see your tracks lost like that.
P.S I am not using your desktop app, just playing through browser. I've also got an account.

**Comment by Zarlex** [comment]
Ok nooo that is too bad. We will of course investigate how this could happen and fix it. Does the playlist still exist and just contains no tracks anymore or did the whole playlist disappear?

**Comment by ParthJai** [comment]
I had created multiple playlists. Its just with this playlist with 60 tracks in it. Yes the playlist is there but nothing exists in it.
Thanx.

**Comment by ParthJai** [comment]
Update: I cannot add songs in this playlist. When I click on "add to playlist" option, I can see that song going to this playlist. But when I reload the page, song just dissapears.

**Comment by Zarlex** [comment]
Your playlist should not be empty anymore now we have found a solution

**Comment by Zarlex** [comment]
Should be fixed with the latest version v5.4.0

**Comment by xtermsoft** [comment]
Can you please upload the new codes to GitHub? Also, when I sign in with my YouTube account, it shows my YouTube playlists and its content but the content has the default Cloud-Player thumbnail and no name of the video. Plus as for your open source API, when I try running it, it says that Mixcloud endpoint was not found (not the exact words, but you get the point). It would be great if you could upload the new version and the updated backend API to GitHub. Thanks a tonne!
