### ISSUE TITLE
failed to install

### ISSUE THREAD

**Issue by yayanheeh** [Cloud-Player/web#78]
![capture-20181115-181842](https://user-images.githubusercontent.com/10670299/48549883-a360bd80-e903-11e8-8771-f95b2f965bfe.png)
I installed this secript, but the results are like the picture, just like that

**Comment by Zarlex** [comment]
```
npm install
npm start
```
Should work

**Comment by Zarlex** [comment]
1. Make sure to clone from the main repository
```
git clone git@github.com:Cloud-Player/web.git
```
2. Install [node.js](https://nodejs.org/en/)
3. run `npm install`
4. run `npm start`
5. Open your browser and go to `localhost:4200` then you should see the working version of [Cloud-Player](https://cloud-player.io)

**Comment by yayanheeh** [comment]
error, permesion denied (public key)

**Comment by yayanheeh** [comment]
is there an easier way to download?... Thanks

**Comment by Zarlex** [comment]
try `git clone https://github.com/Cloud-Player/web.git`

**Comment by yayanheeh** [comment]
I've tried dozens of times, but still can't

**Comment by yayanheeh** [comment]
please check my web https://yayanheeh.github.io/11/src/index.html

**Comment by yayanheeh** [comment]
the result is just like that, thank you, Zarlex

**Comment by Zarlex** [comment]
Before you can host it on a server you have to build it, you can not put the src folder on a server. It is an angular application. Maybe its a good start to read the getting started guide of angular: https://angular.io/guide/quickstart

**Comment by kllod** [comment]
hi

friend you can order, an application for your phone?

how can I contact you to discuss a couple of questions about your engine?
