### ISSUE TITLE
How do you connect with Mixcloud API

### ISSUE THREAD

**Issue by xtermsoft** [Cloud-Player/web#79]
I haven't been able to make sense out of how do you gather the data from Mixcloud because I did not find a single reference to it in your API build and neither did I see an API key. Could you please clarify this since I am a student and learning about API's and stuff. Thanks

**Comment by Zarlex** [comment]
All requests to the mixcloud API are handled by our server. The web UI is sending the requests to our server which is then calling the offical mixcloud api.
You can find a reference to the mixcloud api here: https://www.mixcloud.com/developers
There you can also create your own API key

**Comment by xtermsoft** [comment]
So basically your api server consists of the api key for Mixcloud that handles the requests? Because if that’s the case, I did not see the reference of Mixcloud any where in the code provided up on github. 

Could you please share the code. Thanks.

**Comment by Zarlex** [comment]
You can query tracks from mixcloud by a `GET` request to `https://api.mixcloud.com/search/?q={{YOUR_SEARCH_QUERY}}&type=cloudcast` You don't need an API key for that. You will get tracks from mixcloud that contain `{{YOUR_SEARCH_QUERY}}`. 

For more information please check out the [mixcloud developer documentation](https://www.mixcloud.com/developers)
