### ISSUE TITLE
Feature Request: ability to disable video playback for YouTube

### ISSUE THREAD

**Issue by Romich777** [Cloud-Player/web#81]
YouTube can stream clear audio streams in aac, vorbis and opus formats. So it will be useful to have ability to play only audio tracks, that will decrease bandwidth and battery usage.

In fact I don't know how to get direct audio links from YouTube but it surly possible, regarding to a lot of browser extensions and services, e.g. https://en.savefrom.net/

**Comment by Zarlex** [comment]
We only use the official interface provided by youtube. Of course it is possible but is is against the TOS of youtube
